# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{ cron: "0 * * * *" }]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: { branches: ["master", "main"] }
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: 🎟️ Follow-up of issues and pull requests - Indepth analysis
        uses: lowlighter/metrics@master
        with:
          filename: metrics.plugin.followup.indepth.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_followup: yes
          plugin_followup_indepth: yes
          output_action: none
          delay: 120
          user: MuxinFeng
          plugins_errors_fatal: yes
        if: ${{ success() || failure() }}
